import Link from "next/link";

const metrics = [
  { label: "TRAFFIC ANALYSED", value: "12,481", detail: "↗ +18.4% 24h trend", icon: "◱", tone: "positive" },
  { label: "BOTNET DETECTED", value: "1,284", detail: "● +42.5% spike detected", icon: "△", tone: "orange", alert: true },
  { label: "DETECTION RATE", value: <>10.3<sup>%</sup></>, icon: "%", progress: true },
  { label: "AVG. CONFIDENCE", value: <>94.7<sup>%</sup></>, detail: "High Certainty", icon: "♧", tone: "positive" },
];
const recentAnalyses = [["Flow #05-8941", "Port 443 · TLS Session", "Normal (98.2%)", "normal"], ["Flow #05-8940", "Port 80 · SYN Flooding", "Botnet (91.7%)", "alert"], ["Flow #05-8939", "Port 8080 · API Proxy", "Normal (96.4%)", "normal"], ["Flow #05-8938", "Port 53 · DNS Tunneling", "Botnet (95.1%)", "alert"], ["Flow #05-8937", "Port 443 · Static Asset", "Normal (99.0%)", "normal"]];
function MiniIcon({ children }: { children: React.ReactNode }) { return <span className="mini-icon">{children}</span>; }

export function OverviewDashboard() {
  return <main className="dashboard">
    <section className="hero-card"><div className="eyebrow">● NEURAL TELEMETRY CLASSIFIER <span>SentinelML v2.4.1</span></div><h1>BotSentinel</h1><p className="hero-tagline">Machine Learning-Based Botnet Traffic Detection</p><p className="hero-copy">Autonomous correlation engine isolating distributed botnet anomalies, SYN-flood patterns, and<br className="desktop-break" /> malicious command-and-control beacons from authentic human web traffic.</p><div className="hero-actions"><Link href="/analyze" className="primary-button">Start Traffic Inspection <b>→</b></Link><span><span className="shield">♧</span> Zero False-Positive Target Assurance</span></div></section>
    <section className="metric-grid" aria-label="Network overview">{metrics.map((metric) => <article className={`metric-card ${metric.alert ? "warning-card" : ""}`} key={metric.label}><div className="metric-label">{metric.label}<MiniIcon>{metric.icon}</MiniIcon></div><strong>{metric.value}</strong>{metric.progress ? <><div className="progress-label"><span>Isolation ratio</span><span>1:9.7 packets</span></div><div className="progress"><i /></div></> : <small className={metric.tone}>{metric.detail}{metric.label === "AVG. CONFIDENCE" && <span className="confidence-detail">σ = 0.018</span>}</small>}</article>)}</section>
    <section className="content-grid"><article className="panel traffic-panel"><div className="panel-heading"><div><h2>Traffic Analysis <span className="live-pill">● Live Stream</span></h2><p><b className="teal-dot">●</b> Normalized Traffic (Baseline) <b className="orange-dot">●</b> Botnet Spikes (Flagged)</p></div><div className="time-range"><button>1h</button><button>6h</button><button className="selected">24h</button><button>7d</button></div></div><TrafficChart /><div className="chart-summary"><div><MiniIcon>◉</MiniIcon><span>Peak Botnet Spike<br /><b>342 req/sec</b></span></div><div><MiniIcon>⇄</MiniIcon><span>Inspection Throughput<br /><b>1.2 GB/sec</b></span></div></div></article><aside className="side-stack"><RecentAnalyses /><ThreatDistribution /></aside></section>
    <section className="cta-card"><div><h2>Ready to inspect custom PCAP or real-time network tap?</h2><p>Upload new network packet traces or connect an active eBPF daemon probe to ingest flows instantly.</p></div><div><button className="upload-button">Upload PCAP File</button><Link href="/analyze" className="primary-button compact">Connect Ingest Stream <b>→</b></Link></div></section>
  </main>;
}
function TrafficChart() { return <div className="chart-wrap"><div className="spike-label label-one">342 req/s / Mirai Burst</div><div className="spike-label label-two">342 req/s / Mirai Burst</div><svg viewBox="0 0 650 205" preserveAspectRatio="none" role="img" aria-label="24 hour traffic chart"><defs><linearGradient id="traffic-fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#45c8c0" stopOpacity=".27"/><stop offset="1" stopColor="#45c8c0" stopOpacity=".02"/></linearGradient></defs><path className="gridline" d="M0 45H650M0 102H650M0 160H650" /><path d="M0 158 C42 149 72 127 106 133 S157 149 189 132 S242 105 278 111 S329 126 363 111 S420 89 454 91 S509 82 547 68 S602 45 650 35 L650 188 L0 188Z" fill="url(#traffic-fill)" /><path className="baseline" d="M0 158 C42 149 72 127 106 133 S157 149 189 132 S242 105 278 111 S329 126 363 111 S420 89 454 91 S509 82 547 68 S602 45 650 35" /><path className="spikes" d="M213 158 L251 66 L274 158 M477 158 L491 20 L510 158" /><circle cx="251" cy="66" r="5" className="spike-point"/><circle cx="491" cy="20" r="5" className="spike-point"/></svg><div className="chart-axis"><span>00:00 UTC</span><span>04:00</span><span>08:00</span><span>12:00</span><span>16:00</span><span>20:00</span><span>Now</span></div></div>; }
function RecentAnalyses() { return <article className="panel recent-panel"><div className="panel-title-row"><h2>Recent Analyses <span className="teal-dot">●</span></h2><a href="#all-analyses">View Log</a></div><div className="analysis-list">{recentAnalyses.map(([flow, detail, state, kind]) => <div className="analysis-row" key={flow}><span className={kind === "alert" ? "orange-dot" : "teal-dot"}>◉</span><div><b>{flow}</b><small>{detail}</small></div><em className={kind}>{state}</em>{kind === "alert" && <em className="impact">Impact</em>}</div>)}</div></article>; }
function ThreatDistribution() { return <article className="panel distribution-panel"><h2>Threat Distribution</h2><p>Aggregate classification split across active inspection window</p><div className="distribution-row"><span className="teal-dot">■</span><b>Normal Traffic: 89.7%</b><small>11,197 flows</small></div><div className="wide-bar teal-bar" /><div className="distribution-row"><span className="orange-dot">■</span><b>Botnet Traffic: 10.3%</b><small>1,284 flows</small></div><div className="wide-bar orange-bar" /><h3>IDENTIFIED THREAT VECTORS</h3><div className="vector-grid">{[["41%", "Mirai-like"], ["28%", "HTTP Slowloris"], ["19%", "C2 Beacons"], ["12%", "Brute-Force"]].map(([value, label]) => <div key={label}><b>{value}</b><span>{label}</span></div>)}</div></article>; }
