"use client";

import { useRef, useState } from "react";
import styles from "./analyze-workspace.module.css";

const samples = [
  { name: "Mirai Botnet Traffic (.csv)", detail: "SYN Flood / C2 Telnet Brute-force, 4,280 frames", tag: "ATTACK", icon: "!" },
  { name: "Normal HTTP Browsing (.csv)", detail: "Dual-stack TLS 1.3 / HTTP/2 web egress, 8,912 frames", tag: "BENIGN", icon: "o" },
  { name: "Mixed Flow Test Batch (.csv)", detail: "Simulated DNS tunnel infiltration + CDN cache hits", tag: "HYBRID", icon: "+" },
];
const schema = [["Destination Port", "int32 [0..65535]"], ["Flow Duration", "uint64 (&#181;s)"], ["Total Fwd Packets", "uint32 count"], ["Flow Bytes/s", "float64"], ["Packet Length Mean", "float32 bytes"], ["SYN Flag Count", "uint8 flag"]];

export function AnalyzeWorkspace() {
  const fileInput = useRef<HTMLInputElement>(null);
  const [selectedFile, setSelectedFile] = useState<string | null>(null);
  const [mode, setMode] = useState<"upload" | "manual">("upload");
  const chooseFile = () => fileInput.current?.click();
  const onFile = (file?: File) => setSelectedFile(file?.name ?? null);

  return <main className={`${styles.root} analyze-page`}>
    <section className="analyze-intro"><div><p className="section-kicker">TRAFFIC INGESTION &amp; INFERENCE ENGINE <span>&#8594; XGBoost Multi-Vector v2.4</span></p><h1>Analyze Network Traffic</h1><p>Supply packet captures, flow logs, or manual packet header attributes to evaluate likelihood of botnet intrusion in<br className="desktop-break" /> real time.</p></div><div className="inference-badge"><span>&#9729;</span><div><small>Inference Target</small><b>14ms</b></div><div><small>Active Model</small><b>SentinelML-v2.4</b></div></div></section>
    <div className="analyze-tabs"><button className={mode === "upload" ? "selected" : ""} onClick={() => setMode("upload")}>☁ Upload Dataset (CSV / PCAP)</button><button className={mode === "manual" ? "selected" : ""} onClick={() => setMode("manual")}>☷ Manual Feature Input</button><span>&#9679; Ingestion gateway ready for micro-batch vectors</span></div>
    <section className="analyze-grid"><div className="ingestion-column"><section className="analyze-card upload-card"><input ref={fileInput} type="file" accept=".csv,.pcap,.json" hidden onChange={(event) => onFile(event.target.files?.[0])} />{mode === "upload" ? <div className="drop-zone" onClick={chooseFile} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); onFile(event.dataTransfer.files[0]); }}><span className="upload-cloud">&#9729;</span><h2>{selectedFile ?? "Drop your traffic dataset here or browse files"}</h2><p>Supports <b>.CSV, .PCAP, and .JSON</b> flow dumps up to 50MB<br />CICIDS2017 / Bot-IoT compatible schema.</p><div><button onClick={(event) => { event.stopPropagation(); chooseFile(); }}>&#8679; Upload CSV</button><button onClick={(event) => { event.stopPropagation(); chooseFile(); }}>▣ PCAP Stream Capture</button></div><small className="schema-note">&#9888; Schema requirement: Vector must contain standard forward/backward IP header records.</small></div> : <ManualInput />}</section><DemoDatasets onSelect={setSelectedFile} /></div><aside className="analyze-aside"><SchemaPreview /><InferenceCard selectedFile={selectedFile} /></aside></section>
    <section className="analyze-card specification-card"><div className="spec-heading"><div><h2>Technical Security &amp; Model Specifications</h2><p>Rigorous mathematical telemetry specs for security compliance &amp; zero-trust integration.</p></div><div><span>Latency &#126;14ms</span><span>F1-Score: 0.982</span></div></div><div className="spec-grid"><Spec title="FEATURE NORMALIZATION" text="Input features undergo non-linear standard scaling and log transformation to prevent zero-frequency packet count skewness." /><Spec title="INFERENCE ENGINE" text="Quantized 16-bit Gradient Boosted Trees (XGBoost) combined with a shallow neural embedding layer for sub-15ms decision latency." /><Spec title="PRIVACY &amp; SANDBOX" text="Payload bytes are completely stripped before vector ingestion; only metadata headers (L3/L4) are parsed and evaluated." /><Spec title="STANDARDS COMPLIANCE" text="Fully compatible with CICIDS2017, Bot-IoT, and UNSW-NB15 taxonomy standards for threat vector reporting." /></div></section>
  </main>;
}
function ManualInput() { return <div className="manual-input"><h2>Manual feature vector</h2><p>Enter captured packet telemetry to run an isolated inference.</p><div>{["Destination port", "Flow duration", "Total forward packets", "SYN flag count"].map((label) => <label key={label}>{label}<input placeholder="0" inputMode="numeric" /></label>)}</div><button>Run manual inference &#8594;</button></div>; }
function DemoDatasets({ onSelect }: { onSelect: (name: string) => void }) { return <section className="analyze-card demos-card"><div className="card-heading"><div><h2>Pre-loaded Demo Datasets</h2><p>Benchmark and examine ML with verified honeypot and sandbox telemetries.</p></div><b>INSTANT INJECTION</b></div><div className="demo-grid">{samples.map((sample) => <article key={sample.name}><div><span>{sample.icon}</span><em>{sample.tag}</em></div><h3>{sample.name}</h3><p>{sample.detail}</p><button onClick={() => onSelect(sample.name)}>Load Sample &#8594;</button></article>)}</div></section>; }
function SchemaPreview() { return <section className="analyze-card schema-card"><div className="card-heading"><h2>Schema Preview</h2><b>CICIDS2017</b></div><p>Parsed incoming files are mapped to the 78-dimensional network flow vector. Key mandatory attributes:</p><div className="schema-list">{schema.map(([name, type]) => <div key={name}><b>{name}</b><span dangerouslySetInnerHTML={{ __html: type }} /></div>)}</div><small>&#10003; Automatic MinMax feature normalization applied</small></section>; }
function InferenceCard({ selectedFile }: { selectedFile: string | null }) { return <section className="analyze-card inference-card"><p>&#9679; INFERENCE READINESS: READY</p><div className="file-ready"><span>▧</span><div><b>{selectedFile ?? "Mirai Botnet Traffic (.csv)"}</b><small>{selectedFile ? "Dataset staged for model inference" : "4,280 flows parsed"}</small></div><span>&#10003;</span></div><button>☊ &nbsp; ANALYZE TRAFFIC &#8594;</button><small>Execution runs against local web-assembly SentinelML model and or secure neural cluster.</small></section>; }
function Spec({ title, text }: { title: string; text: string }) { return <div><h3>{title}</h3><p>{text}</p></div>; }
